// flow-typed signature: 17b7b58aa4297d94d82c69b3183fcad4
// flow-typed version: <<STUB>>/rollup-plugin-multidest_v~1.0.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-multidest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-multidest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'rollup-plugin-multidest/index' {
  declare module.exports: $Exports<'rollup-plugin-multidest'>;
}
declare module 'rollup-plugin-multidest/index.js' {
  declare module.exports: $Exports<'rollup-plugin-multidest'>;
}
